#!/usr/bin/env python3
"""Cross-check the existing 2,928-domain audit against connector-sourced data.

The originating thread could not reach Semrush or Ahrefs (connectors showed
`enabledInChat: false`), so every verdict outside the 50k CSV sample rested on
domain-level metrics alone. This script folds in what the connectors return:

  semrush_backlinks_filtered.csv  link-level rows for the unsampled profile,
                                  including `response_code` and `redirect_url`
                                  which the CSV export never carried
  ahrefs_refdomains.csv           live referring domains with `traffic_domain`
                                  and `positions_source_domain` — the source
                                  organic traffic the audit listed as its
                                  single biggest blind spot
  ahrefs_is_spam.csv              Ahrefs' own spam determination
  ahrefs_ghost_domains.csv        zero-traffic, zero-ranking, high-link domains

It does not re-run the audit: the two original CSV exports are not present in
this container, so `audit.py` and `refdomain_audit.py` cannot be replayed. What
it produces instead is an overlay — proposed verdict changes with the evidence
for each — that can be applied when the exports are re-supplied.

Usage:
    python3 crosscheck.py <outdir>
"""
import csv
import os
import re
import sys
from collections import Counter, defaultdict
from urllib.parse import urlsplit

from audit import BRAND_OWNED, _registrable, host_of

# Cloudflare and other shared front-end ranges. Domains behind these share an
# "IP" that says nothing about common ownership — the same trap the original
# audit hit with Shopify's 23.227.38.0/24, which held the client's own estate.
# Clustering on them would manufacture networks out of unrelated sites.
SHARED_FRONTEND_PREFIXES = (
    "104.16.", "104.17.", "104.18.", "104.19.", "104.20.", "104.21.",
    "104.22.", "104.23.", "104.24.", "104.25.", "104.26.", "104.27.",
    "172.64.", "172.65.", "172.66.", "172.67.", "162.159.", "198.41.",
    "188.114.96.", "188.114.97.", "188.114.98.", "188.114.99.",
    "23.227.38.",          # Shopify — client's own brand estate
    "151.101.", "142.250.", "34.149.", "76.76.21.", "192.0.7",
)

# Domain-name families that are machine-generated by construction: a fixed stem
# plus an enumerated suffix. Unlike the name-shape scorer the audit rejected as
# too false-positive-prone, these are exact structural matches, not guesses.
GENERATED_FAMILIES = (
    (re.compile(r"^seo-anomaly-"), "seo-anomaly network"),
    (re.compile(r"^seo-cartel-"), "seo-cartel network"),
    (re.compile(r"^bhs-links-[a-z]{2}\.xyz$"), "bhs-links sibling network"),
    (re.compile(r"^(page|link|rank|seo|google|organic|domain|toprank|nexa|"
                r"guestpost|backlink|premium|pbn|prime)[a-z]*\.shop$"),
     "SEO-vendor .shop network"),
)


# Verdicts whose stated basis is the redirect or affiliate-gateway reasoning.
# A brand-owned hop is only exculpatory for these: it says "this redirect is
# first-party", which speaks to nothing else. Domains disavowed for a hosting
# footprint or a directory network were never judged on their redirect at all,
# so a brand-owned hop is irrelevant to them and must not overturn the verdict.
REDIRECT_BASED_RISK = (
    "Synthetic Affiliate Doorway Domain",
)


def shared_frontend(ip):
    return bool(ip) and ip.startswith(SHARED_FRONTEND_PREFIXES)


def num(v, default=0):
    try:
        return int(float(str(v).replace(",", "").strip()))
    except (TypeError, ValueError):
        return default


def truthy(v):
    return str(v).strip().lower() in ("1", "true", "yes")


def load(path, key):
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as fh:
        return {r[key]: r for r in csv.DictReader(fh)}


def generated_family(domain):
    for pat, label in GENERATED_FAMILIES:
        if pat.search(domain):
            return label
    return None


def main(outdir):
    audit = load("out/full_refdomain_audit.csv", "Referring Domain")
    ahrefs = load("ahrefs_refdomains.csv", "domain")
    spam = load("ahrefs_is_spam.csv", "domain")
    ghost = load("ahrefs_ghost_domains.csv", "domain")

    # Merge the targeted slices into the enumerated set; the slices carry the
    # same fields and reach domains the partitioned enumeration did not.
    for extra in (spam, ghost):
        for d, r in extra.items():
            ahrefs.setdefault(d, r)

    # ---- link-level evidence from the Semrush pull ------------------------
    links = defaultdict(list)
    with open("semrush_backlinks_filtered.csv", encoding="utf-8") as fh:
        for r in csv.DictReader(fh, delimiter=";"):
            links[_registrable(host_of(r["source_url"]))].append(r)

    rows, changes = [], []
    for domain in sorted(set(audit) | set(ahrefs)):
        a = audit.get(domain)
        h = ahrefs.get(domain)
        lk = links.get(domain, [])

        traffic = num(h.get("traffic_domain"), -1) if h else -1
        positions = num(h.get("positions_source_domain"), -1) if h else -1
        dofollow = num(h.get("dofollow_links"), 0) if h else 0
        is_spam = truthy(h.get("is_spam")) if h else False
        ip = (h.get("ip_source") or "").strip() if h else ""

        statuses = Counter(num(r["response_code"]) for r in lk)
        dead = sum(n for c, n in statuses.items() if c in (0, 404, 410))
        hops = [r["redirect_url"].strip() for r in lk if r["redirect_url"].strip()]
        hop_hosts = Counter(_registrable(host_of(u)) for u in hops)
        brand_hop = any(hh in BRAND_OWNED for hh in hop_hosts)

        family = generated_family(domain)
        current = a["Action Recommendation"] if a else "NOT_AUDITED"

        # --- proposed change, most protective rule first ------------------
        proposal, reason, confidence = None, None, None
        ghost = traffic == 0 and positions == 0 and dofollow >= 50
        # Independent grounds to distrust the domain, none of which a redirect
        # through the client's own estate can answer.
        spam_evidence = bool(family) or is_spam or ghost
        risk = a["Primary Risk Factor"] if a else ""

        if domain in BRAND_OWNED:
            if current == "DISAVOW":
                proposal, confidence = "KEEP_AFFILIATE_RETAIN", "High"
                reason = "Domain is in the client's own brand estate."
        elif family:
            proposal, confidence = "DISAVOW", "High"
            reason = f"Machine-generated domain family: {family}."
        elif ghost:
            proposal, confidence = "DISAVOW", "High"
            reason = (f"{dofollow} follow links from a domain with zero organic "
                      "traffic and zero ranking keywords — no audience to pass "
                      "real equity, consistent with a doorway/PBN footprint.")
        elif is_spam and current != "DISAVOW":
            # The audit consumes no third-party toxicity score, by design, and
            # Ahrefs' is_spam earns that caution: it fires on brandfetch.com
            # and za.com, both with >1M monthly organic visits. A domain with a
            # real audience and real rankings is not a dead PBN whatever a
            # vendor flag says, so above these thresholds the flag only buys a
            # look, never a disavow. This is the same shape as the audit's
            # existing branded-anchor and anchor-diversity brakes.
            if traffic >= 500 or positions >= 100:
                proposal, confidence = "REVIEW_MANUALLY", "Low"
                reason = (f"Ahrefs flags this as spam, but it has {traffic:,} "
                          f"monthly organic visits and {positions:,} ranking "
                          "keywords. The flag conflicts with the traffic; "
                          "resolve by hand rather than on the vendor score.")
            else:
                proposal, confidence = "DISAVOW", "Medium"
                reason = ("Ahrefs flags the referring domain as spam and it has "
                          "no meaningful organic traffic or rankings to "
                          "contradict that; the audit's domain-level metrics "
                          "never reached it.")
        elif (brand_hop and current == "DISAVOW"
              and risk in REDIRECT_BASED_RISK and not spam_evidence):
            proposal, confidence = "REVIEW_MANUALLY", "Medium"
            reason = (f"Disavowed as '{risk}', but the links route through "
                      f"{'/'.join(h for h in sorted(hop_hosts) if h in BRAND_OWNED)}"
                      " — the client's own estate. The redirect that drove this "
                      "verdict is first-party, so the basis no longer holds.")

        if proposal and proposal != current:
            changes.append({
                "Referring Domain": domain,
                "Current Action": current,
                "Proposed Action": proposal,
                "Confidence": confidence,
                "Ahrefs Traffic": traffic if traffic >= 0 else "",
                "Ahrefs Positions": positions if positions >= 0 else "",
                "Follow Links": dofollow,
                "Ahrefs is_spam": is_spam,
                "IP": ip,
                "Reason": reason,
            })

        rows.append({
            "Referring Domain": domain,
            "In Semrush Audit": bool(a),
            "In Ahrefs Live": bool(h),
            "Current Action": current,
            "Link-Level Rows (new)": len(lk),
            "Dead/Unreachable Links": dead,
            "Redirect Hosts": ";".join(sorted(hop_hosts)),
            "Brand-Owned Hop": brand_hop,
            "Ahrefs Traffic": traffic if traffic >= 0 else "",
            "Ahrefs Positions": positions if positions >= 0 else "",
            "Ahrefs Follow Links": dofollow,
            "Ahrefs is_spam": is_spam,
            "IP": ip,
            "Generated Family": family or "",
        })

    os.makedirs(outdir, exist_ok=True)
    with open(f"{outdir}/crosscheck_full.csv", "w", newline="",
              encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0]))
        w.writeheader()
        w.writerows(rows)
    with open(f"{outdir}/proposed_changes.csv", "w", newline="",
              encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=list(changes[0]))
        w.writeheader()
        w.writerows(sorted(changes, key=lambda r: -num(r["Follow Links"])))

    # ---- non-shared-IP clustering over domains the audit never saw -------
    clusters = defaultdict(list)
    for r in rows:
        if not r["In Semrush Audit"] and r["IP"] and not shared_frontend(r["IP"]):
            clusters[r["IP"]].append(r["Referring Domain"])
    real = {ip: ds for ip, ds in clusters.items() if len(ds) >= 2}

    newly = [r for r in rows if r["Link-Level Rows (new)"] > 0]
    unaudited = [r for r in rows if not r["In Semrush Audit"]]
    print(f"domains considered:            {len(rows)}")
    print(f"newly carrying link evidence:  {len(newly)}")
    print(f"present in Ahrefs, not audited:{len(unaudited)}")
    print(f"proposed verdict changes:      {len(changes)}")
    for k, v in Counter((c["Current Action"], c["Proposed Action"])
                        for c in changes).most_common():
        print(f"    {k[0]:22s} -> {k[1]:22s} {v}")
    print(f"dead/unreachable links:        "
          f"{sum(r['Dead/Unreachable Links'] for r in rows)}")
    print(f"shared-IP clusters (non-CDN):  {len(real)}")
    for ip, ds in sorted(real.items(), key=lambda kv: -len(kv[1]))[:8]:
        print(f"    {ip:16s} {len(ds)}  {', '.join(sorted(ds)[:4])}")
    print(f"\nWritten: {outdir}/crosscheck_full.csv, {outdir}/proposed_changes.csv")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "out")
